var universities = [
    { "Title": "Abertay University", "Country": "UK" },
    { "Title": "Aberystwyth University", "Country": "UK" },
    { "Title": "Amity University London", "Country": "UK" },
    { "Title": "Arts University Bournemouth", "Country": "UK" },
    { "Title": "Arden University", "Country": "UK" },
    { "Title": "Aston University", "Country": "UK" },
    { "Title": "Bangor University", "Country": "UK" },
    { "Title": "Bath Spa University", "Country": "UK" },
    { "Title": "BIMM Institute", "Country": "UK" },
    { "Title": "Bournemouth University", "Country": "UK" },
    { "Title": "Brunel University", "Country": "UK" },
    { "Title": "Canterbury Christ Church University", "Country": "UK" },
    { "Title": "Cardiff Metropolitan University", "Country": "UK" },
    { "Title":"City University of London","Country":"UK"},
    { "Title":"Coventry University","Country":"UK"},
    { "Title":"Cranfield University","Country":"UK"},
    {"Title":"Edinburgh Napier University","Country":"UK"},
    {"Title":"Edinburgh College of Art (ECA)","Country":"UK"},
    {"Title":"Falmouth University","Country":"UK"},
    {"Title":"Glasgow Caledonian University","Country":"UK"},
    {"Title":"Henley Business School","Country":"UK"},
    {"Title":"Heriot Watt University","Country":"UK"},
    {"Title":"Hult International Business School","Country":"UK"},
    {"Title":"Istituto Marangoni","Country":"UK"},
    {"Title":"Keele University","Country":"UK"},
    {"Title":"Kings College London","Country":"UK"},
    {"Title":"Kingston University","Country":"UK"},
    {"Title":"Lancaster University","Country":"UK"},
    {"Title":"Le Corden Bleu","Country":"UK"},
    {"Title":"Leeds Arts University","Country":"UK"},
    {"Title":"Leeds Beckett University","Country":"UK"},
    {"Title":"Liverpool Hope University","Country":"UK"},
    {"Title":"London School of Business and Finance","Country":"UK"},
    {"Title":"London South Bank University","Country":"UK"},
    {"Title":"Loughborough University","Country":"UK"},
    {"Title":"Manchester Metropolitan","Country":"UK"},
    {"Title":"Middlesex University","Country":"UK"},
    {"Title":"Napier University","Country":"UK"},
    {"Title":"Newcastle University","Country":"UK"},
    {"Title":"Northeastern University","Country":"UK"},
    {"Title":"Nottingham Trent University","Country":"UK"},
    {"Title":"Oxford Brookes University","Country":"UK"},
    {"Title":"Oxford Summer Courses Limited","Country":"UK"},
    {"Title":"QA Higher Education","Country":"UK"},
    {"Title":"University of Plymouth","Country":"UK"},
    {"Title":"Queen Margaret University","Country":"UK"},
    {"Title":"Queen Mary University of London","Country":"UK"},
    {"Title":"Queens University Belfast","Country":"UK"},
    {"Title":"Regents University","Country":"UK"},
    {"Title":"Robert Gordon University","Country":"UK"},
    {"Title":"Roehampton University","Country":"UK"},
    {"Title":"Royal Agricultural University","Country":"UK"},
    {"Title":"Royal Holloway University of London","Country":"UK"},
    {"Title":"School of Oriental and African Studies","Country":"UK"},
    {"Title":"Sheffield Hallam University","Country":"UK"},
    {"Title":"SP Jain University","Country":"UK"},
    {"Title":"Staffordshire University","Country":"UK"},
    {"Title":"Swansea University","Country":"UK"},
    {"Title":"TEDI-London","Country":"UK"},
    {"Title":"Teesside University","Country":"UK"},
    {"Title":"The London Film School","Country":"UK"},
    {"Title":"The University of Law","Country":"UK"},
    {"Title":"The University of Northumbria at Newcastle","Country":"UK"},
    {"Title":"UA92","Country":"UK"},
    {"Title":"University for the Creative Arts","Country":"UK"},
    {"Title":"University of Aberdeen","Country":"UK"},
    {"Title":"University of Arts London","Country":"UK"},
    {"Title":"University of Bedfordshire","Country":"UK"},
    {"Title":"University of Birmingham","Country":"UK"},
    {"Title":"University of Birbeck","Country":"UK"},
    {"Title":"University of Bolton","Country":"UK"},
    {"Title":"University of Bradford","Country":"UK"},
    {"Title":"University of Brighton","Country":"UK"},
    {"Title":"University of Bristol","Country":"UK"},
    {"Title":"University of Buckingham","Country":"UK"},
    {"Title":"University of Chester","Country":"UK"},
    {"Title":"University of Chichester","Country":"UK"},
    {"Title":"University of College Birmingham","Country":"UK"},
    {"Title":"University of Creative Arts","Country":"UK"},
    {"Title":"University of Derby","Country":"UK"},
    {"Title":"University of Dundee","Country":"UK"},
    {"Title":"University of Edinburgh","Country":"UK"},
    {"Title":"University of Essex","Country":"UK"},
    {"Title":"University of Exeter","Country":"UK"},
    {"Title":"University of Glasgow","Country":"UK"},
    {"Title":"University of Gloucestershire","Country":"UK"},
    {"Title":"University of Greenwich","Country":"UK"},
    {"Title":"University of Hertfordshire","Country":"UK"},
    {"Title":"University of Huddersfield","Country":"UK"},
    {"Title":"University of Kent","Country":"UK"},
    {"Title":"University of Leeds","Country":"UK"},
    {"Title":"University of Leicester","Country":"UK"},
    {"Title":"University of Lincoln","Country":"UK"},
    {"Title":"University of Liverpool","Country":"UK"},
    {"Title":"University of Manchester","Country":"UK"},
    {"Title":"University of Northampton","Country":"UK"},
    {"Title":"University of Nottingham","Country":"UK"},
    {"Title":"University of Reading","Country":"UK"},
    {"Title":"University of Salford","Country":"UK"},
    {"Title":"University of Sheffield","Country":"UK"},
    {"Title":"University of South Wales","Country":"UK"},
    {"Title":"University of Southampton","Country":"UK"},
    {"Title":"University of Stirling","Country":"UK"},
    {"Title":"University of Strathclyde","Country":"UK"},
    // {"Title":"University of Sunderland","Country":"UK"},
    {"Title":"University Of Surrey","Country":"UK"},
    {"Title":"University of Sussex","Country":"UK"},
    {"Title":"University of Ulster","Country":"UK"},
    {"Title":"University of West London","Country":"UK"},
    {"Title":"University of Westminster","Country":"UK"},
    {"Title":"University of Winchester","Country":"UK"},
    {"Title":"University of York","Country":"UK"},

    {"Title":"Academy of Art University","Country":"USA"},
    {"Title":"Alliant International University (CSML","Country":"USA"},
    {"Title":"American Musical and Dramatic Academy","Country":"USA"},
    {"Title":"American University - Washington DC","Country":"USA"},
    {"Title":"Arizona State university","Country":"USA"},
    {"Title":"Arkansas State University","Country":"USA"},
    {"Title":"Arkansas Tech University","Country":"USA"},
    {"Title":"Ashland University","Country":"USA"},
    {"Title":"Auburn Institute at Montgomery","Country":"USA"},
    {"Title":"Augustana University","Country":"USA"},
    {"Title":"Barry University","Country":"USA"},
    {"Title":"Berkeley College","Country":"USA"},
    {"Title":"Bowling Green State University","Country":"USA"},
    {"Title":"Bradley University","Country":"USA"},
    {"Title":"Brooklyn College","Country":"USA"},
    {"Title":"California Flight Academy","Country":"USA"},
    {"Title":"California International Business University","Country":"USA"},
    {"Title":"California Lutheran University","Country":"USA"},
    {"Title":"California State University Bakersfield","Country":"USA"},
    {"Title":"California State University Channel Islands","Country":"USA"},
    {"Title":"California State University Dominguez Hills","Country":"USA"},
    {"Title":"California State University East Bay","Country":"USA"},
    {"Title":"California State University Fresno","Country":"USA"},
    {"Title":"California State University Humboldt State","Country":"USA"},
    {"Title":"California State University Long Beach","Country":"USA"},
    {"Title":"California State University Monterey Bay","Country":"USA"},
    {"Title":"California State University Northridge","Country":"USA"},
    {"Title":"California State University Sacramento","Country":"USA"},
    {"Title":"California State University San Bernardino","Country":"USA"},
    {"Title":"California State University San Marcos","Country":"USA"},
    {"Title":"California State University Sonoma","Country":"USA"},
    {"Title":"Catholic University of America","Country":"USA"},
    {"Title":"Chatham University","Country":"USA"},
    {"Title":"City University of Seattle","Country":"USA"},
    {"Title":"Claremont Graduate University","Country":"USA"},
    {"Title":"Clark University","Country":"USA"},
    {"Title":"Clarkson University","Country":"USA"},
    {"Title":"Cleveland Insitute of Art","Country":"USA"},
    {"Title":"College of Staten Island CUNY","Country":"USA"},
    {"Title":"College of the Canyons","Country":"USA"},
    {"Title":"Colorado State University","Country":"USA"},
    {"Title":"Concordia University Chicago","Country":"USA"},
    {"Title":"Concordia University Wisconsin","Country":"USA"},
    {"Title":"Creighton University","Country":"USA"},
    {"Title":"Culinary Institute of America","Country":"USA"},
    {"Title":"Dallas Baptist University","Country":"USA"},
    {"Title":"Daniels College of Businesss University of Denver","Country":"USA"},
    {"Title":"DePaul University","Country":"USA"},
    {"Title":"Devry University","Country":"USA"},
    {"Title":"Drew University","Country":"USA"},
    {"Title":"Drury University","Country":"USA"},
    {"Title":"Duke University","Country":"USA"},
    {"Title":"Duquesne University","Country":"USA"},
    {"Title":"East Texas Baptist University","Country":"USA"},
    {"Title":"ECPI University","Country":"USA"},
    {"Title":"Elmhurst University","Country":"USA"},
    {"Title":"Elmira College","Country":"USA"},
    {"Title":"Embry Riddle Aeronautical University Daytona Beach","Country":"USA"},
    {"Title":"Embry Riddle Aeronautical University Presscott","Country":"USA"},
    {"Title":"Fairfield University","Country":"USA"},
    {"Title":"Fairleigh Dickinson University","Country":"USA"},
    {"Title":"Fisher College","Country":"USA"},
    {"Title":"Florida Agricultural and Mechanical University","Country":"USA"},
    {"Title":"Florida Atlantic University","Country":"USA"},
    {"Title":"Florida Gulf Coast University","Country":"USA"},
    {"Title":"Florida Institute of Technology","Country":"USA"},
    {"Title":"Florida International University","Country":"USA"},
    {"Title":"Florida Polytechnic University","Country":"USA"},
    {"Title":"Fontbonne University","Country":"USA"},
    {"Title":"Foothill-De Anza Community College","Country":"USA"},
    {"Title":"Fordham University","Country":"USA"},
    {"Title":"Full Sail University","Country":"USA"},
    {"Title":"Gannon University","Country":"USA"},
    {"Title":"George Fox University","Country":"USA"},
    {"Title":"George Mason University","Country":"USA"},
    {"Title":"Grand Valley State University","Country":"USA"},
    {"Title":"Hawaii Pacific University","Country":"USA"},
    {"Title":"Herzing University","Country":"USA"},
    {"Title":"Hofstra University","Country":"USA"},
    {"Title":"Hood College","Country":"USA"},
    {"Title":"Horizon University","Country":"USA"},
    {"Title":"Hult International Business School","Country":"USA"},
    {"Title":"Illinois Institute of Technology","Country":"USA"},
    {"Title":"Illnios State University","Country":"USA"},
    {"Title":"Indiana Institute of Technology","Country":"USA"},
    {"Title":"Indiana University-Purdue University","Country":"USA"},
    {"Title":"Institute of Culinary Education","Country":"USA"},
    {"Title":"Iowa State University","Country":"USA"},
    {"Title":"IPERC","Country":"USA"},
    {"Title":"Jacksonville State University","Country":"USA"},
    {"Title":"Jacksonville University","Country":"USA"},
    {"Title":"James Madison University","Country":"USA"},
    {"Title":"Jessup University","Country":"USA"},
    {"Title":"John Cabot University","Country":"USA"},
    {"Title":"Johnson Wales University","Country":"USA"},
    {"Title":"Kansas State University","Country":"USA"},
    {"Title":"Kansas State University Polytechnic Campus","Country":"USA"},
    {"Title":"Kent State University","Country":"USA"},
    {"Title":"Kennesaw State University","Country":"USA"},
    {"Title":"Lawrence Technological University","Country":"USA"},
    {"Title":"Le Cordon Bleu","Country":"USA"},
    {"Title":"LIM College","Country":"USA"},
    {"Title":"Lincoln University","Country":"USA"},
    {"Title":"Long Island University Brooklyn","Country":"USA"},
    {"Title":"Long Island University-Post","Country":"USA"},
    {"Title":"Manhattan College","Country":"USA"},
    {"Title":"Manhattan Institute Of Management","Country":"USA"},
    {"Title":"Marist College","Country":"USA"},
    {"Title":"Marshall University","Country":"USA"},
    {"Title":"Marywood University","Country":"USA"},
    {"Title":"Massachussets College of Pharmacy and Health Sciences","Country":"USA"},
    {"Title":"Mercer University Atlanta","Country":"USA"},
    {"Title":"Mercy College","Country":"USA"},
    {"Title":"Merrimack College","Country":"USA"},
    {"Title":"Miami International University of Art and Design","Country":"USA"},
    {"Title":"Miami University Ohio","Country":"USA"},
    {"Title":"Midwestern State University","Country":"USA"},
    {"Title":"Midwestern University","Country":"USA"},
    {"Title":"Milwaukee School of Engineering","Country":"USA"},
    {"Title":"Mississippi State University","Country":"USA"},
    {"Title":"Missouri State University","Country":"USA"},
    {"Title":"Missouri University of Science and Technology","Country":"USA"},
    {"Title":"Monmouth University New Jersey","Country":"USA"},
    {"Title":"Montana State University","Country":"USA"},
    {"Title":"Montana State University Billings","Country":"USA"},
    {"Title":"Montana State University Bozeman","Country":"USA"},
    {"Title":"Musicians Institute: College of Contemporary Music","Country":"USA"},
    {"Title":"New England College","Country":"USA"},
    {"Title":"New Jersey City University","Country":"USA"},
    {"Title":"New Jersey Institute of Technology","Country":"USA"},
    {"Title":"New School of Architecture","Country":"USA"},
    {"Title":"New York Conservatory for Dramatic Arts","Country":"USA"},
    {"Title":"New York Film Academy","Country":"USA"},
    {"Title":"New York Institute of Technology","Country":"USA"},
    {"Title":"New York University SPS","Country":"USA"},
    {"Title":"New York University Steinhardt","Country":"USA"},
    {"Title":"Niagara University","Country":"USA"},
    {"Title":"North Park University","Country":"USA"},
    {"Title":"Northeastern Illinois University","Country":"USA"},
    {"Title":"Northeastern University","Country":"USA"},
    {"Title":"Northern Arizona University","Country":"USA"},
    {"Title":"Northern Michigan University","Country":"USA"},
    {"Title":"Northwest Missouri State University","Country":"USA"},
    {"Title":"Northwood University","Country":"USA"},
    {"Title":"Ohio Dominican University","Country":"USA"},
    {"Title":"Ohio Northern University","Country":"USA"},
    {"Title":"Ohio University","Country":"USA"},
    {"Title":"Ohlone College","Country":"USA"},
    {"Title":"Oklahoma City University","Country":"USA"},
    {"Title":"Old Dominion University","Country":"USA"},
    {"Title":"Oregon State University","Country":"USA"},
    {"Title":"Pace University","Country":"USA"},
    {"Title":"Pacific Lutheran University","Country":"USA"},
    {"Title":"Park University","Country":"USA"},
    {"Title":"Pepperdine University","Country":"USA"},
    {"Title":"Pittsburg State University","Country":"USA"},
    {"Title":"Portland State University","Country":"USA"},
    {"Title":"Post University","Country":"USA"},
    {"Title":"Purdue University-Northwest","Country":"USA"},
    {"Title":"Quinnipiac University","Country":"USA"},
    {"Title":"Radford University","Country":"USA"},
    {"Title":"Regis University","Country":"USA"},
    {"Title":"Richard Bland College of William Mary","Country":"USA"},
    {"Title":"Rider University","Country":"USA"},
    {"Title":"Robert Morris University","Country":"USA"},
    {"Title":"Rochester Institute of Technology","Country":"USA"},
    {"Title":"Roger Williams University","Country":"USA"},
    {"Title":"Roosevelt University","Country":"USA"},
    {"Title":"Sacred Heart University","Country":"USA"},
    {"Title":"Saginaw Valley State University","Country":"USA"},
    {"Title":"Saint Leo University","Country":"USA"},
    {"Title":"Saint Louis University","Country":"USA"},
    {"Title":"Salem College","Country":"USA"},
    {"Title":"San Diego Flight Training International","Country":"USA"},
    {"Title":"San Diego State University","Country":"USA"},
    {"Title":"San Francisco State University","Country":"USA"},
    {"Title":"San Jose State University","Country":"USA"},
    {"Title":"Savannah College of Art and Design","Country":"USA"},
    {"Title":"Seattle Pacific University","Country":"USA"},
    {"Title":"Seattle University","Country":"USA"},
    {"Title":"Seton Hall University","Country":"USA"},
    {"Title":"Shorelight","Country":"USA"},
    {"Title":"Simmons University","Country":"USA"},
    {"Title":"Southeast Missouri State University","Country":"USA"},
    {"Title":"Southern Connecticut State University","Country":"USA"},
    {"Title":"Southern Methodist University","Country":"USA"},
    {"Title":"Southern New Hampshire University","Country":"USA"},
    {"Title":"Southern Utah University","Country":"USA"},
    {"Title":"Spartan College of Aeronautics & Technology","Country":"USA"},
    {"Title":"St Johns University","Country":"USA"},
    {"Title":"State University of New York Alfred State College","Country":"USA"},
    {"Title":"State University of New York Binghamton University","Country":"USA"},
    {"Title":"State University of New York Brockport","Country":"USA"},
    {"Title":"State University of New York Buffalo State College","Country":"USA"},
    {"Title":"State University of New York Fredonia","Country":"USA"},
    {"Title":"State University of New York Geneseo","Country":"USA"},
    {"Title":"State University of New York Morrisville IPPC","Country":"USA"},
    {"Title":"State University of New York New Paltz","Country":"USA"},
    {"Title":"State University of New York Oneonta","Country":"USA"},
    {"Title":"State University of New York Oswego","Country":"USA"},
    {"Title":"State University of New York Plattsburgh","Country":"USA"},
    {"Title":"State University of New York Polytechnic Institute","Country":"USA"},
    {"Title":"State University of New York Potsdam","Country":"USA"},
    {"Title":"State University of New York State University College at Old Westbury","Country":"USA"},
    {"Title":"State University of New York University at Albany","Country":"USA"},
    {"Title":"Stevens Institute of Technology","Country":"USA"},
    {"Title":"Suffolk University","Country":"USA"},
    {"Title":"SUNY-State University College at Purchase","Country":"USA"},
    {"Title":"Temple University Philadelphia","Country":"USA"},
    {"Title":"Texas A And M University Corpus Christi","Country":"USA"},
    {"Title":"Texas A And M University Kingsville","Country":"USA"},
    {"Title":"Texas State University","Country":"USA"},
    {"Title":"Texas Tech University","Country":"USA"},
    {"Title":"The Art Institutes","Country":"USA"},
    {"Title":"The Chicago School of Professional Psychology","Country":"USA"},
    {"Title":"The University of Akron","Country":"USA"},
    {"Title":"The University of Oklahoma","Country":"USA"},
    {"Title":"The University of North Florida","Country":"USA"},
    {"Title":"Thomas College","Country":"USA"},
    {"Title":"Thomas Jefferson University","Country":"USA"},
    {"Title":"Troy University","Country":"USA"},
    {"Title":"Truman State University","Country":"USA"},
    {"Title":"UCSC Silicon Valley Extension","Country":"USA"},
    {"Title":"University of Alabama Birmingham","Country":"USA"},
    {"Title":"University of Alabama Huntsville","Country":"USA"},
    {"Title":"University of Alabama Tuscaloosa","Country":"USA"},
    {"Title":"University of Arizona","Country":"USA"},
    {"Title":"University of Bridgeport","Country":"USA"},
    {"Title":"University of Californi Irvine","Country":"USA"},
    {"Title":"University of California - Berkeley Extension","Country":"USA"},
    {"Title":"University of California-Riverside","Country":"USA"},
    {"Title":"University of Cincinnati","Country":"USA"},
    {"Title":"University of Colorado at Denver","Country":"USA"},
    {"Title":"University of Connecticut","Country":"USA"},
    {"Title":"University of Delaware","Country":"USA"},
    {"Title":"University of Findlay","Country":"USA"},
    {"Title":"University Of Hartford","Country":"USA"},
    {"Title":"University of Houston","Country":"USA"},
    {"Title":"University of Houston - Clear Lake","Country":"USA"},
    {"Title":"University of Idaho","Country":"USA"},
    {"Title":"University of Indianapolis","Country":"USA"},
    {"Title":"University of Maine","Country":"USA"},
    {"Title":"University of Maryland Baltimore County","Country":"USA"},
    {"Title":"University of Massachusetts Amherst","Country":"USA"},
    {"Title":"University of Massachusetts Dartmouth","Country":"USA"},
    {"Title":"University of Memphis","Country":"USA"},
    {"Title":"University of Miami","Country":"USA"},
    {"Title":"University of Michigan Flint","Country":"USA"},
    {"Title":"University of Missouri St Louis","Country":"USA"},
    {"Title":"University of Nebraska Lincoln","Country":"USA"},
    {"Title":"University of Nevada Las Vegas","Country":"USA"},
    {"Title":"University of Nevada Reno","Country":"USA"},
    {"Title":"University of New Hampshire","Country":"USA"},
    {"Title":"University of New Haven","Country":"USA"},
    {"Title":"University of North Alabama","Country":"USA"},
    {"Title":"University of North Carolina at Greensboro","Country":"USA"},
    {"Title":"University of North Carolina at Wilmington","Country":"USA"},
    {"Title":"University of North Texas","Country":"USA"},
    {"Title":"University of Oregon","Country":"USA"},
    {"Title":"University of Portland","Country":"USA"},
    {"Title":"University of Rhode Island","Country":"USA"},
    {"Title":"University of Scranton","Country":"USA"},
    {"Title":"University of South Alabama","Country":"USA"},
    {"Title":"University of South Caroline Upstate","Country":"USA"},
    {"Title":"University of Tampa","Country":"USA"},
    {"Title":"University of Tennessee Knoxville","Country":"USA"},
    {"Title":"University of Texas At Arlington","Country":"USA"},
    {"Title":"University of Texas-San Antonio","Country":"USA"},
    {"Title":"University of the Arts","Country":"USA"},
    {"Title":"University Of The Science In Philadelphia","Country":"USA"},
    {"Title":"University of West Alabama","Country":"USA"},
    {"Title":"University of West Florida","Country":"USA"},
    {"Title":"University of Wisconsin Eau Claire","Country":"USA"},
    {"Title":"University of Wisconsin Milwaukee","Country":"USA"},
    {"Title":"University of Wisconsin Stevens Point","Country":"USA"},
    {"Title":"University of Wisconsin Stout","Country":"USA"},
    {"Title":"University of Wisconsin Whitewater","Country":"USA"},
    {"Title":"US Aviation Academy","Country":"USA"},
    {"Title":"Valparaiso University","Country":"USA"},
    {"Title":"Vatel USA","Country":"USA"},
    {"Title":"Washington College","Country":"USA"},
    {"Title":"Washington State University","Country":"USA"},
    {"Title":"Washington University of Science and Technology","Country":"USA"},
    {"Title":"Webster University","Country":"USA"},
    {"Title":"Western Washington University","Country":"USA"},
    {"Title":"Wichita State University","Country":"USA"},
    {"Title":"Wilkes University","Country":"USA"},
    {"Title":"Wilmington University","Country":"USA"},
    {"Title":"Woodbury University","Country":"USA"},
    {"Title":"Xavier University","Country":"USA"},
    {"Title":"Academy of Learning","Country":"Canada"},
    {"Title":"Acadia University","Country":"Canada"},
    {"Title":"Acsenda School of Management","Country":"Canada"},
    {"Title":"Alexander College","Country":"Canada"},
    {"Title":"Algoma University","Country":"Canada"},
    {"Title":"Algonquin College","Country":"Canada"},
    {"Title":"Arbutus College","Country":"Canada"},
    {"Title":"Ascent College of Technology","Country":"Canada"},
    {"Title":"Assiniboine Community College","Country":"Canada"},
    {"Title":"Brock University","Country":"Canada"},
    {"Title":"Cambrian College","Country":"Canada"},
    {"Title":"Camosun College","Country":"Canada"},
    {"Title":"Canadian College of Technology and Business","Country":"Canada"},
    {"Title":"Cape Breton University","Country":"Canada"},
    {"Title":"Capilano University","Country":"Canada"},
    {"Title":"CEGEP","Country":"Canada"},
    {"Title":"Cegep De La GaspésieetDes Iles","Country":"Canada"},
    {"Title":"Centennial College","Country":"Canada"},
    {"Title":"College Of The Rockies","Country":"Canada"},
    {"Title":"Concordia University Of Edmonton","Country":"Canada"},
    {"Title":"Conestoga College","Country":"Canada"},
    {"Title":"Confederation College","Country":"Canada"},
    {"Title":"Coquitlam College","Country":"Canada"},
    {"Title":"Crandall University","Country":"Canada"},
    {"Title":"Dalhousie University","Country":"Canada"},
    {"Title":"Douglas College","Country":"Canada"},
    {"Title":"Durham College","Country":"Canada"},
    {"Title":"Fanshawe College","Country":"Canada"},
    {"Title":"Fraser International College SFU","Country":"Canada"},
    {"Title":"George Brown College","Country":"Canada"},
    {"Title":"Georgian College","Country":"Canada"},
    {"Title":"Georgian ILAC","Country":"Canada"},
    {"Title":"Herzing College","Country":"Canada"},
    {"Title":"Humber College","Country":"Canada"},
    {"Title":"Huron College","Country":"Canada"},
    {"Title":"International College of Manitoba","Country":"Canada"},
    {"Title":"International Business University","Country":"Canada"},
    {"Title":"Justice Institute of British Columbia","Country":"Canada"},
    {"Title":"Kings University College At The University Of Western Ontario","Country":"Canada"},
    {"Title":"Kwantlen Polytechnic University","Country":"Canada"},
    {"Title":"Lakehead University","Country":"Canada"},
    {"Title":"Lakeland College","Country":"Canada"},
    {"Title":"Lambton College","Country":"Canada"},
    {"Title":"Langara College","Country":"Canada"},
    {"Title":"LaSalle College","Country":"Canada"},
    {"Title":"Le Cordon Bleu","Country":"Canada"},
    {"Title":"Loyalist College","Country":"Canada"},
    {"Title":"Manitoba Institute of Trades and Technology","Country":"Canada"},
    {"Title":"Matrix College","Country":"Canada"},
    {"Title":"Medicine Hat College","Country":"Canada"},
    {"Title":"Memorial University of New Foundland","Country":"Canada"},
    {"Title":"Mohawk College","Country":"Canada"},
    {"Title":"Mount Allison University","Country":"Canada"},
    {"Title":"Mount Saint Vincent University","Country":"Canada"},
    {"Title":"New Brunswick Community College","Country":"Canada"},
    {"Title":"New York Institute of Techonology Vancouver","Country":"Canada"},
    {"Title":"Niagara College","Country":"Canada"},
    {"Title":"Niagara College Toronto","Country":"Canada"},
    {"Title":"Niagara University","Country":"Canada"},
    {"Title":"Nippissing University","Country":"Canada"},
    {"Title":"Norquest College","Country":"Canada"},
    {"Title":"North Island College","Country":"Canada"},
    {"Title":"Northeastern University","Country":"Canada"},
    {"Title":"Northern Lights College","Country":"Canada"},
    {"Title":"Northwest Community College","Country":"Canada"},
    {"Title":"OCAD University","Country":"Canada"},
    {"Title":"Olds College","Country":"Canada"},
    {"Title":"Ontario Tech University","Country":"Canada"},
    {"Title":"Pacific Coast Community College","Country":"Canada"},
    {"Title":"Pacific Link College","Country":"Canada"},
    {"Title":"Parkland College","Country":"Canada"},
    {"Title":"Portage College at Campbell College","Country":"Canada"},
    {"Title":"Red River College","Country":"Canada"},
    {"Title":"Royal Roads University","Country":"Canada"},
    {"Title":"Rutherford Private School","Country":"Canada"},
    {"Title":"Saskatchewan Polytechnic University","Country":"Canada"},
    {"Title":"Sault College","Country":"Canada"},
    {"Title":"Selkirk College","Country":"Canada"},
    {"Title":"Seneca College","Country":"Canada"},
    {"Title":"Sheridan College","Country":"Canada"},
    {"Title":"Sprott Shaw College","Country":"Canada"},
    {"Title":"St. Clair","Country":"Canada"},
    {"Title":"St Marys University","Country":"Canada"},
    {"Title":"St. Lawrence College","Country":"Canada"},
    {"Title":"St. Thomas University","Country":"Canada"},
    {"Title":"St.Francis Xavier University","Country":"Canada"},
    {"Title":"The Kings University Edmonton","Country":"Canada"},
    {"Title":"The Northern Alberta Institute of Technology","Country":"Canada"},
    {"Title":"The Southern Alberta Institute of Technology","Country":"Canada"},
    {"Title":"The University of Guelph","Country":"Canada"},
    {"Title":"The University of Lethbridge","Country":"Canada"},
    {"Title":"The University of Northern British Columbia","Country":"Canada"},
    {"Title":"Thompson Rivers University","Country":"Canada"},
    {"Title":"Toronto Film School","Country":"Canada"},
    {"Title":"Toronto Metropolitan University International College","Country":"Canada"},
    {"Title":"Toronto School of Management","Country":"Canada"},
    {"Title":"Trebas Institute","Country":"Canada"},
    {"Title":"Trent University","Country":"Canada"},
    {"Title":"Trinity Western University","Country":"Canada"},
    {"Title":"University Canada West","Country":"Canada"},
    {"Title":"University of Alberta","Country":"Canada"},
    {"Title":"University of Manitoba","Country":"Canada"},
    {"Title":"University of Niagara Falls","Country":"Canada"},
    {"Title":"University of New Brunswick","Country":"Canada"},
    {"Title":"University Of Regina","Country":"Canada"},
    {"Title":"University Of Saskatchewan","Country":"Canada"},
    {"Title":"University of the Fraser Valley","Country":"Canada"},
    {"Title":"University of Victoria","Country":"Canada"},
    {"Title":"University of Waterloo","Country":"Canada"},
    {"Title":"University Of Windsor","Country":"Canada"},
    {"Title":"University of Winnipeg","Country":"Canada"},
    {"Title":"Vancouver Film School","Country":"Canada"},
    {"Title":"Vancouver Institute of Media Arts","Country":"Canada"},
    {"Title":"Vancouver Island University","Country":"Canada"},
    {"Title":"Vanier College","Country":"Canada"},
    {"Title":"Wilfrid Laurier International College","Country":"Canada"},
    {"Title":"Wilfrid Laurier University","Country":"Canada"},
    {"Title":"York College of Applied Studies","Country":"Canada"},
    // {"Title":"Yukon College","Country":"Canada"},
    {"Title":"ANU College","Country":"Australia"},
    {"Title":"Australian Catholic University","Country":"Australia"},
    {"Title":"Australian National Airline College","Country":"Australia"},
    {"Title":"Australian Technical And Management College","Country":"Australia"},
    {"Title":"Bond University","Country":"Australia"},
    {"Title":"Canterbury Education Group","Country":"Australia"},
    {"Title":"Canterbury Institute of Management","Country":"Australia"},
    {"Title":"Central Queensland University","Country":"Australia"},
    {"Title":"Charles Darwin University","Country":"Australia"},
    {"Title":"Charles Darwin University Pathway College","Country":"Australia"},
    {"Title":"Charles Sturt University","Country":"Australia"},
    {"Title":"Charles Sturt University Study Centre","Country":"Australia"},
    {"Title":"Curtin College","Country":"Australia"},
    {"Title":"Curtin University","Country":"Australia"},
    {"Title":"Deakin College","Country":"Australia"},
    {"Title":"Deakin University","Country":"Australia"},
    {"Title":"Edith Cowan College","Country":"Australia"},
    {"Title":"Edith Cowan University","Country":"Australia"},
    {"Title":"Engineering Institute of Technology","Country":"Australia"},
    {"Title":"Eynesbury College","Country":"Australia"},
    {"Title":"Flinders ISC","Country":"Australia"},
    {"Title":"Griffith College","Country":"Australia"},
    {"Title":"Griffith University","Country":"Australia"},
    {"Title":"James Cook University Brisbane","Country":"Australia"},
    {"Title":"James Cook University Australia","Country":"Australia"},
    {"Title":"Kaplan International","Country":"Australia"},
    {"Title":"La Trobe University International College","Country":"Australia"},
    {"Title":"La Trobe University Sydney Campus","Country":"Australia"},
    {"Title":"Le Cordon Bleu","Country":"Australia"},
    {"Title":"Macquarie University","Country":"Australia"},
    {"Title":"Monash University","Country":"Australia"},
    {"Title":"Murdoch University","Country":"Australia"},
    {"Title":"NAVITAS SAE Institute ACAP","Country":"Australia"},
    {"Title":"NAVITAS SIBT","Country":"Australia"},
    {"Title":"RMIT Royal Melbourne Institute of Technology","Country":"Australia"},
    {"Title":"Southern Cross University","Country":"Australia"},
    {"Title":"Stanley College","Country":"Australia"},
    {"Title":"Study Group","Country":"Australia"},
    {"Title":"Swinburne University of Technology","Country":"Australia"},
    {"Title":"Taylors College Auckland","Country":"Australia"},
    {"Title":"Taylors College Perth","Country":"Australia"},
    {"Title":"The Hotel School SCU","Country":"Australia"},
    {"Title":"The University of Adelaide","Country":"Australia"},
    {"Title":"The University of Adelaide College","Country":"Australia"},
    {"Title":"The University of Sydney","Country":"Australia"},
    {"Title":"Torrens University Billy Blue College of Design","Country":"Australia"},
    {"Title":"Torrens University Blue Mountains International Hotel Management School","Country":"Australia"},
    {"Title":"Trinity College","Country":"Australia"},
    {"Title":"University of Melbourne","Country":"Australia"},
    {"Title":"University of New South Wales","Country":"Australia"},
    {"Title":"University of Newcastle","Country":"Australia"},
    {"Title":"University Of Queensland","Country":"Australia"},
    {"Title":"University of South Australia","Country":"Australia"},
    {"Title":"University of Southern Queensland","Country":"Australia"},
    {"Title":"University of Sunshine Coast","Country":"Australia"},
    {"Title":"University of Tasmania Pathway College","Country":"Australia"},
    {"Title":"University of Tasmania","Country":"Australia"},
    {"Title":"University of Western Australia","Country":"Australia"},
    {"Title":"University of Western Sydney","Country":"Australia"},
    {"Title":"University of Wollongong","Country":"Australia"},
    {"Title":"UP Education","Country":"Australia"},
    {"Title":"UTS College","Country":"Australia"},
    {"Title":"Western Sydney University International College","Country":"Australia"},
    {"Title":"Western Sydney University Sydney City Campus","Country":"Australia"},
    {"Title":"AGI Education LTD","Country":"New Zealand"},
    {"Title":"Aspire 2 International","Country":"New Zealand"},
    {"Title":"Auckland Institute of Studies At St Helens","Country":"New Zealand"},
    {"Title":"Auckland University of Technology","Country":"New Zealand"},
    {"Title":"Australian Technical and Management College","Country":"New Zealand"},
    {"Title":"Eastern Institute Of Technology","Country":"New Zealand"},
    {"Title":"Future Skills NewZeland","Country":"New Zealand"},
    {"Title":"ICL education","Country":"New Zealand"},
    {"Title":"International Aviation Academy of New Zealand","Country":"New Zealand"},
    {"Title":"International College of Auckland","Country":"New Zealand"},
    {"Title":"International College Of Linguistics","Country":"New Zealand"},
    {"Title":"International Pacific College","Country":"New Zealand"},
    {"Title":"Le Corden Bleu","Country":"New Zealand"},
    {"Title":"Lifeway College","Country":"New Zealand"},
    {"Title":"Lincoln University","Country":"New Zealand"},
    {"Title":"Kaplan","Country":"New Zealand"},
    {"Title":"Manukau Institute of Technology","Country":"New Zealand"},
    {"Title":"Massey University","Country":"New Zealand"},
    {"Title":"Media Design School","Country":"New Zealand"},
    {"Title":"NAVITAS University of Canterburry International College","Country":"New Zealand"},
    {"Title":"Nelson Marlborough Institute of Technology","Country":"New Zealand"},
    {"Title":"New Zealand Airline Academy Limited","Country":"New Zealand"},
    {"Title":"New Zealand Institute of Business and Technology","Country":"New Zealand"},
    {"Title":"New Zealand School of Travel And Tourism","Country":"New Zealand"},
    {"Title":"New Zealand Tertiary College","Country":"New Zealand"},
    {"Title":"North Tec","Country":"New Zealand"},
    {"Title":"Northshore International Academy","Country":"New Zealand"},
    {"Title":"Otago Polytechnic","Country":"New Zealand"},
    {"Title":"Pacific International Hotel Management School","Country":"New Zealand"},
    {"Title":"Professional Business &amp; Restaurant School","Country":"New Zealand"},
    {"Title":"Queenstown Resort College","Country":"New Zealand"},
    {"Title":"SAE Institue Auckland","Country":"New Zealand"},
    {"Title":"Southern Institute Of Technology","Country":"New Zealand"},
    {"Title":"Tai Poutini Polytechnic","Country":"New Zealand"},
    {"Title":"Te Pukenga","Country":"New Zealand"},
    {"Title":"Toi Ohomai Institute of Technology","Country":"New Zealand"},
    {"Title":"The Future Skills Academy","Country":"New Zealand"},
    {"Title":"Unitec","Country":"New Zealand"},
    {"Title":"Universal College of Learning","Country":"New Zealand"},
    {"Title":"University of Auckland","Country":"New Zealand"},
    {"Title":"University of Canterbury","Country":"New Zealand"},
    {"Title":"University of Otago","Country":"New Zealand"},
    {"Title":"University of Waikato","Country":"New Zealand"},
    {"Title":"UP Education","Country":"New Zealand"},
    {"Title":"Victoria University Of Wellington","Country":"New Zealand"},
    {"Title":"Waikato Institute of Technology","Country":"New Zealand"},
    {"Title":"Wellington Institute Of Technology","Country":"New Zealand"},
    {"Title":"Western Institute of Technology at Taranaki","Country":"New Zealand"},
    {"Title":"Whitecliff College of Arts and Design","Country":"New Zealand"},
    {"Title":"Whitireia Polytechnic","Country":"New Zealand"},
    {"Title":"Wintec Waikato","Country":"New Zealand"},
    {"Title":"Yobee School of Design","Country":"New Zealand"},
    {"Title":"Amity University","Country":"Singapore"},
    {"Title":"At Sunrice GlobalChef Academy","Country":"Singapore"},
    {"Title":"Curtin Singapore","Country":"Singapore"},
    {"Title":"Embry Riddle Aeronautical University","Country":"Singapore"},
    {"Title":"German Institute of Science and Technology TUM Asia","Country":"Singapore"},
    {"Title":"HTMi","Country":"Singapore"},
    {"Title":"James Cook University","Country":"Singapore"},
    {"Title":"Kaplan Higher Education Academie","Country":"Singapore"},
    {"Title":"Lasalle College of the Arts","Country":"Singapore"},
    {"Title":"London School of Buisness and Finance","Country":"Singapore"},
    {"Title":"Management Development Institute of Singapore","Country":"Singapore"},
    {"Title":"Nanyang Institute Of Management","Country":"Singapore"},
    {"Title":"Nanyang Technological University","Country":"Singapore"},
    {"Title":"National University Of Singapore","Country":"Singapore"},
    {"Title":"PSB Academy","Country":"Singapore"},
    {"Title":"Raffles College of Higher Education","Country":"Singapore"},
    {"Title":"Raffles Education Network","Country":"Singapore"},
    {"Title":"School D Hospitality","Country":"Singapore"},
    {"Title":"Singapore Institute of Management","Country":"Singapore"},
    {"Title":"Singapore Institute of Technology","Country":"Singapore"},
    {"Title":"Singapore Institute of Technology & Design","Country":"Singapore"},
    {"Title":"Singapore Management University","Country":"Singapore"},
    {"Title":"SP Jain University","Country":"Singapore"},
    {"Title":"School D' Hospitality","Country":"Singapore"},
    {"Title":"Atlantic Technological University","Country":"Ireland"},
    {"Title":"Dublin Business School","Country":"Ireland"},
    {"Title":"Dublin City University","Country":"Ireland"},
    // {"Title":"Dublin Institute of Technology","Country":"Ireland"},
    {"Title":"Dundalk Institute Of Technology","Country":"Ireland"},
    {"Title":"Galway Mayo Institute of Technology","Country":"Ireland"},
    {"Title":"Griffith College Dublin","Country":"Ireland"},
    {"Title":"IBAT Ireland","Country":"Ireland"},
    {"Title":"Maynooth University","Country":"Ireland"},
    {"Title":"Munster Technological University","Country":"Ireland"},
    {"Title":"National College Of Ireland","Country":"Ireland"},
    {"Title":"Shannon College of Hotel Management","Country":"Ireland"},
    {"Title":"South East Technological University","Country":"Ireland"},
    {"Title":"Technological University Dublin","Country":"Ireland"},
    {"Title":"Technological University of the Shannon","Country":"Ireland"},
    {"Title":"Trinity college of Dublin","Country":"Ireland"},
    {"Title":"University College Cork","Country":"Ireland"},
    {"Title":"University College Dublin","Country":"Ireland"},
    {"Title":"University of Limerick","Country":"Ireland"},
    {"Title":"Aivancity","Country":"France"},
    {"Title":"Audencia Business School","Country":"France"},
    {"Title":"Aura International School of Management","Country":"France"},
    {"Title":"College De Paris","Country":"France"},
    {"Title":"Ducasse Education","Country":"France"},
    {"Title":"Ecole Conte","Country":"France"},
    {"Title":"EM Normandie Business School","Country":"France"},
    {"Title":"ESDES Lyon business school","Country":"France"},
    {"Title":"Esigelec Grande Ecole - School of Engineering","Country":"France"},
    {"Title":"ESSCA School of Management","Country":"France"},
    {"Title":"ICN Business School France","Country":"France"},
    {"Title":"IDRAC Business school","Country":"France"},
    {"Title":"ISC Paris Business School","Country":"France"},
    {"Title":"Isep Grande Eecole d ingenieurs du numerique","Country":"France"},
    {"Title":"ISTEC Business school","Country":"France"},
    {"Title":"Istituto Marangoni","Country":"France"},
    {"Title":"KEDGE Business School","Country":"France"},
    {"Title":"Keyce Business School","Country":"France"},
    {"Title":"Le Cordon Bleu","Country":"France"},
    {"Title":"Leonard de Vinci Group","Country":"France"},
    {"Title":"Montpellier Business School","Country":"France"},
    {"Title":"Neoma Business School","Country":"France"},
    {"Title":"OMNES Education","Country":"France"},
    {"Title":"Paris School of Luxury","Country":"France"},
    {"Title":"Rennes School of Business","Country":"France"},
    {"Title":"SKEMA Business School","Country":"France"},
    {"Title":"Schellhammer Business School","Country":"France"},
    {"Title":"Berlin School of Business and Innovation","Country":"Germany"},
    {"Title":"CBS International Business School","Country":"Germany"},
    {"Title":"EU Business School","Country":"Germany"},
    {"Title":"GISMA","Country":"Germany"},
    {"Title":"ISM International School of Management Germany","Country":"Germany"},
    {"Title":"IU International University of Applied Sciences","Country":"Germany"},
    {"Title":"IUBH University of Applied Sciences","Country":"Germany"},
    {"Title":"Lancaster University Leipzig","Country":"Germany"},
    {"Title":"Macromedia Gmbh","Country":"Germany"},
    {"Title":"Munich Business School","Country":"Germany"},
    {"Title":"Mediadesign Hochschule","Country":"Germany"},
    {"Title":"mdh University of Applied Sciences","Country":"Germany"},
    {"Title":"New European College","Country":"Germany"},
    {"Title":"Rheinland Privatschule","Country":"Germany"},
    {"Title":"HS Fresenius University of Applied Sciences","Country":"Germany"},
    {"Title":"Hochschule Fur Okenomie And Management GmbH","Country":"Germany"},
    {"Title":"Sprachen Berlin","Country":"Germany"},
    {"Title":"SRH Berlin University of Applied Sciences","Country":"Germany"},
    {"Title":"Steinbeis School of Management and Innovation","Country":"Germany"},
    {"Title":"University of Europe Applied Sciences","Country":"Germany"},
    {"Title":"University Targu Mures Medical Campus Hamburg","Country":"Germany"},
    {"Title":"BHMS","Country":"Switzerland"},
    {"Title":"Cesar RITZ College","Country":"Switzerland"},
    {"Title":"Culinary Arts Academy","Country":"Switzerland"},
    {"Title":"École Ducasse","Country":"Switzerland"},
    {"Title":"EU Business School","Country":"Switzerland"},
    {"Title":"Hotel Institute Montreux","Country":"Switzerland"},
    {"Title":"HTMI","Country":"Switzerland"},
    {"Title":"Glion","Country":"Switzerland"},
    {"Title":"Indian School of Hospitality","Country":"Switzerland"},
    {"Title":"Invictus","Country":"Switzerland"},
    {"Title":"Le Roches","Country":"Switzerland"},
    // {"Title":"Sommet Education","Country":"Switzerland"},
    {"Title":"Swiss Hotel Management School","Country":"Switzerland"},
    {"Title":"Swiss School of Business and Management Geneva","Country":"Switzerland"},
    {"Title":"Abu Dhabi University","Country":"Dubai"},
    {"Title":"American University in Dubai","Country":"Dubai"},
    {"Title":"Amity Global Institute","Country":"Dubai"},
    {"Title":"Canadian University Dubai","Country":"Dubai"},
    {"Title":"Curtin University","Country":"Dubai"},
    {"Title":"De Montfort University","Country":"Dubai"},
    {"Title":"EM Normandie","Country":"Dubai"},
    {"Title":"Heriot Watt University","Country":"Dubai"},
    {"Title":"HTMI","Country":"Dubai"},
    {"Title":"Hult International Business School","Country":"Dubai"},
    {"Title":"IMT Business School Dubai","Country":"Dubai"},
    {"Title":"Manipal University","Country":"Dubai"},
    {"Title":"Middlesex University","Country":"Dubai"},
    {"Title":"Modul University","Country":"Dubai"},
    {"Title":"Murdoch University","Country":"Dubai"},
    {"Title":"New York Institute of Technology","Country":"Dubai"},
    {"Title":"Rochester Institute of Technology","Country":"Dubai"},
    {"Title":"SIC Manipal Education","Country":"Dubai"},
    {"Title":"Symboisis International University","Country":"Dubai"},
    {"Title":"The Emirates Academy of Hospitality Management","Country":"Dubai"},
    {"Title":"University of Birmingham","Country":"Dubai"},
    {"Title":"University of Bolton - Dubai Campus","Country":"Dubai"},
    {"Title":"University of Wollongong","Country":"Dubai"},
    {"Title":"Audencia Business School","Country":"Spain"},
    {"Title":"Campus Spain","Country":"Spain"},
    {"Title":"Castelldefels School of Social Sciences","Country":"Spain"},
    {"Title":"CS3 Business School","Country":"Spain"},
    {"Title":"EAE Business School","Country":"Spain"},
    {"Title":"EU Business School","Country":"Spain"},
    {"Title":"IAE Business School","Country":"Spain"},
    {"Title":"IHMGS","Country":"Spain"},
    {"Title":"Asia Pacific University of Technology and Innovation","Country":"Malaysia"},
    {"Title":"Curtin University","Country":"Malaysia"},
    {"Title":"Heriot Watt","Country":"Malaysia"},
    {"Title":"Le Corden Bleu","Country":"Malaysia"},
    {"Title":"Limkokwing University","Country":"Malaysia"},
    {"Title":"Manipal University College","Country":"Malaysia"},
    {"Title":"Malaysia University of Science and Technology","Country":"Malaysia"},
    {"Title":"Manipal International University","Country":"Malaysia"},
    {"Title":"Newcastle University Medicine Malaysia","Country":"Malaysia"},
    {"Title":"SEGi College","Country":"Malaysia"},
    {"Title":"Swinburne University of Technology","Country":"Malaysia"},
    {"Title":"University Of Nottingham","Country":"Malaysia"},
    {"Title":"University of Reading","Country":"Malaysia"},
    {"Title":"University Of Southampton","Country":"Malaysia"},
    {"Title":"University of Wollongong","Country":"Malaysia"},
    {"Title":"AEA Training Centre","Country":"Mauritius"},
    {"Title":"Amity University","Country":"Mauritius"},
    {"Title":"MDIS Vels","Country":"India"},
    {"Title":"Universal Business School","Country":"India"},
    {"Title":"SP Jain University Mumbai","Country":"India"},
    {"Title":"Global School","Country":"Netherlands"},
    {"Title":"Nyenrode Business Universiteit","Country":"Netherlands"},
    {"Title":"The Hague University of Applied Sciences","Country":"Netherlands"},
    {"Title":"University of Amsterdam","Country":"Netherlands"},
    {"Title":"University of Twente","Country":"Netherlands"},
    {"Title":"Wittenborg University of Applied Sciences","Country":"Netherlands"},
    {"Title":"Domus Academy Milan","Country":"Italy"},
    {"Title":"Istituto Marangoni","Country":"Italy"},
    {"Title":"Naba Milan","Country":"Italy"},
    // {"Title":"Nottingham Trent University","Country":"Online Degrees"},
    // {"Title":"University of Birmingham","Country":"Online Degrees"},
    // {"Title":"University of Glasgow","Country":"Online Degrees"},

    {"Title":"Ascencia Business School Malta","Country":"International"},
    {"Title":"America University of Malta","Country":"International"},
    {"Title":"American University of the Caribbean St Maarten","Country":"International"},
    {"Title":"Amity Global Business School Mauritius China India","Country":"International"},
    {"Title":"David Tvildiani Medical University - Georgia","Country":"International"},
    {"Title":"Hult International Business School China","Country":"International"},
    {"Title":"Global School, Netherlands","Country":"International"},
    {"Title":"Le Cordon Bleu Thailand","Country":"International"},
    {"Title":"Modul University Austria","Country":"International"},
    {"Title":"Monash University South Africa","Country":"International"},
    {"Title":"Nyenrode Business Universiteit, Netherlands","Country":"International"},
    {"Title":"Ross University Domicia","Country":"International"},
    {"Title":"SRH Haarlem University of Applied Sciences","Country":"International"},
    {"Title":"St Georges University Grenada","Country":"International"},
    {"Title":"The Hague Uni. of Applied Science, Netherlands","Country":"International"},
    {"Title":"University Admissions (UA Portugal","Country":"International"},
    {"Title":"University of Amsterdam, Netherland","Country":"International"},
    {"Title":"University of Central Lancashire Cyprus","Country":"International"},
    {"Title":"University of Twente, Netherlands","Country":"International"},
    {"Title":"University of Tartu Estonia","Country":"International"},
    {"Title":"Webster College Greece","Country":"International"},
    {"Title":"Webster College Netherlands","Country":"International"},
    {"Title":"Webster University Georgia","Country":"International"},
    {"Title":"Wittenborg University of Applied Sciences Netherlands","Country":"International"},


    
];
